/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx,ts,tsx}', './global.css'],

  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        primary: 'var(--primary)',
        'primary-hover': 'var(--primary-hover)',
        'primary-foreground': 'var(--primary-foreground)',
        secondary: 'var(--secondary)',
        'secondary-foreground': 'var(--secondary-foreground)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        accent: 'var(--accent)',
        'accent-foreground': 'var(--accent-foreground)',
        destructive: 'var(--destructive)',
        'destructive-foreground': 'var(--destructive-foreground)',
        safe: 'var(--safe)',
        'safe-foreground': 'var(--safe-foreground)',
        'safe-muted': 'var(--safe-muted)',
        border: 'var(--border)',
      },
      fontFamily: {
        head: ['ArchivoBlack_400Regular'],
        sans: ['SpaceGrotesk_400Regular'],
        'sans-light': ['SpaceGrotesk_300Light'],
        'sans-medium': ['SpaceGrotesk_500Medium'],
        'sans-semibold': ['SpaceGrotesk_600SemiBold'],
        'sans-bold': ['SpaceGrotesk_700Bold'],
      },
      borderRadius: {
        none: '0px',
        sm: '0px',
        DEFAULT: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      boxShadow: {
        xs: '1px 1px 0 0 var(--border)',
        sm: '2px 2px 0 0 var(--border)',
        DEFAULT: '3px 3px 0 0 var(--border)',
        md: '4px 4px 0 0 var(--border)',
        lg: '6px 6px 0 0 var(--border)',
        xl: '10px 10px 0 1px var(--border)',
        '2xl': '16px 16px 0 1px var(--border)',
      },
    },
  },
  plugins: [],
};
